# Generated by Django 3.1.2 on 2020-10-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='genre',
            field=models.ManyToManyField(to='recipe.Genre'),
        ),
    ]
