# Generated by Django 3.1.2 on 2020-10-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20201017_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='product',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(default=0, help_text='재료의 양', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='none', help_text='재료의 이름', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
