# Generated by Django 3.1.2 on 2020-10-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20201015_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='profile',
            field=models.ImageField(blank=True, help_text='요리에 대한 사진', upload_to=''),
        ),
    ]
